function plotgeom(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 28-Jul-2022 22:51:30

% Create figure
figure1 = figure('Position',[100 100 100+800 100+400],'NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'r-','DisplayName','Area','LineWidth',2);
% Create ylabel
ylabel('Area [m^2]','FontName','Times New Roman');

% Set the remaining axes properties
set(axes1,'YColor','r');
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X1,sqrt(Y1/pi),'b-','DisplayName','Radius','LineWidth',2);

% Create ylabel
ylabel('Radius [m]','FontName','Times New Roman');

% Set the remaining axes properties
set(axes1,'YColor','b');
% Create xlabel
xlabel('Position [m]','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 1.05*max(X1)]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on','YGrid',...
    'on');
