function plotcompSPLFFT(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 01-Aug-2022 20:47:51

% Create figure
figure1 = figure('Position',[100 100 100+800 100+600],'NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1,'Color',[0 0 0]);

[pks,locs] = findpeaks(Y1,X1,'MinPeakProminence',20);

plot(locs,pks,'x','MarkerSize',10,'Marker','x','LineStyle','none','Color',[1 0 0]);

for i=1:length(locs)
    text(locs(i)+50,pks(i),num2str(round(locs(i))),'FontName','Times New Roman');
end

% Create ylabel
ylabel('Sound pressure level [dBSPL] at 1 [m] ref. 20 [\muPa]');

% Create xlabel
xlabel('Frequency [Hz]');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 5000]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[20 120]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on','YGrid',...
    'on');
