function plotcompSPL(X1, Y1, X2, Y2, X3, Y3,f_l,f_u,scale_x)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 29-Jul-2022 23:56:12

% Create figure
figure1 = figure('Position',[100 100 100+800 100+600],'NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

plot(X1,Y1,'DisplayName','MATLAB-Simlink','LineWidth',2,'Color',[0 0 0]);

[pks,locs] = findpeaks(Y1,X1);

plot(locs,pks,'x','MarkerSize',10,'Marker','x','LineWidth',2,'LineStyle','none','Color',[0 1 0],'HandleVisibility','off');

for i=1:length(locs)
    text(locs(i)+50,pks(i),num2str(round(locs(i))),'FontName','Times New Roman');
end

plot(X2,Y2,'DisplayName','LTspice','LineStyle',':','LineWidth',2,'Color',[1 0 0]);
plot(X3,Y3,'DisplayName','COMSOL','LineStyle','--','LineWidth',2,'Color',[0 0 1]);

% Create ylabel
ylabel('Sound pressure level [dBSPL] at 1 [m] ref. 20 [\muPa]');

% Create xlabel
xlabel('Frequency [Hz]');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[f_l f_u]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on',...
    'XMinorTick','on','XScale',scale_x,'YGrid','on','YMinorTick','on','YScale',...
    'linear');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'NumColumns',3,'Location','northoutside');