function REIM = readCOMSOLRX(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ACRADIATIONCOMSOL = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ACRADIATIONCOMSOL = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ACRadiationCOMSOL = importfile("C:\Users\김웅지\OneDrive - postech.ac.kr\Aa - Ongoing Project\211201 ~ 221130 - INFAC Horn\D -Simulink\SHD\1_acoustical components\AC_Radiation_COMSOL_LTspice\AC_Radiation_COMSOL.txt", [9, 508]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2022-08-01 16:33:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Freq", "RX"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
Temp = readtable(filename, opts);
REIM = [Temp.Freq(1:500) Temp.RX(1:500) Temp.RX(501:1000)];

end