function VecAvgS23 = readExpFA(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VECAVGS23 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  VECAVGS23 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  VecAvgS23 = importfile("C:\Users\kimwo\OneDrive - postech.ac.kr\Aa - Ongoing Project\211201 ~ 221130 - INFAC Horn\D -Simulink\SHD\2_mechanical components\ME_Diaphragm_3DOF_linear_COMSOL_LTspice\VecAvgS2-3.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2022-10-22 20:23:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["freq", "acc", "Var3"];
opts.SelectedVariableNames = ["freq", "acc"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "freq", "TrimNonNumeric", true);
opts = setvaropts(opts, "freq", "ThousandsSeparator", ",");

% Import the data
VecAvgS23 = readtable(filename, opts);

end