function REIM = readLTspiceRX(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ACRADIATION = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  ACRADIATION = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ACRadiation = importfile("C:\Users\김웅지\OneDrive - postech.ac.kr\Aa - Ongoing Project\211201 ~ 221130 - INFAC Horn\D -Simulink\SHD\1_acoustical components\AC_Radiation_COMSOL_LTspice\AC_Radiation.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2022-08-01 16:30:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", ","];

% Specify column names and types
opts.VariableNames = ["Freq", "R", "X"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Freq", "R", "X"], "ThousandsSeparator", ",");

% Import the data
REIM = readtable(filename, opts);

end