function resultCOMSOL = readCOMSOL(filename, dataLines)
%IMPORTFILE Import data from a text file
%  AC220722COMPRESSOR2DXOPENEABSZ = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  AC220722COMPRESSOR2DXOPENEABSZ = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  AC220722Compressor2DXopeneabsZ = importfile("C:\Users\김웅지\OneDrive - postech.ac.kr\Aa - Ongoing Project\211201 ~ 221130 - INFAC Horn\D -Simulink\SHD\acoustical components\AC_Compressor_COMSOL_LTspice\AC -220722 - Compressor, 2DX, open(e), abs(Z).txt", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2022-07-22 20:05:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["freq", "value"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
resultCOMSOL = readtable(filename, opts);

end