function plotcompFD(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 20-Oct-2022 21:45:12

% Create figure
figure1 = figure('Position',[100 100 100+800 100+600],'NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','MATLAB-Simulink','LineWidth',2,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'DisplayName','COMSOL','LineWidth',2,'LineStyle','--',...
    'Color',[0 0 1]);

% Create plot
plot(X3,Y3,'DisplayName','Experiment','LineWidth',2,'LineStyle','-.',...
    'Color',[1 0 1]);

% Create ylabel
ylabel('Force [N]');

% Create xlabel
xlabel('Displacement [m]');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-0.001 0.001]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on','YGrid',...
    'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Orientation','horizontal','Location','northoutside');

