function MENonlineartranslationalspringExperiment220901 = readExpFD(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MENONLINEARTRANSLATIONALSPRINGEXPERIMENT220901 = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as a table.
%
%  MENONLINEARTRANSLATIONALSPRINGEXPERIMENT220901 = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MENonlineartranslationalspringExperiment220901 = importfile("C:\Users\김웅지\OneDrive - postech.ac.kr\Aa - Ongoing Project\211201 ~ 221130 - INFAC Horn\D -Simulink\SHD\2_mechanical components\ME_Nonlinear_translational_spring_Experiment\ME_Nonlinear_translational_spring_Experiment_220901.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2022-10-20 20:54:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["d", "f"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
MENonlineartranslationalspringExperiment220901 = readtable(filename, opts);

end